import type { RoomData } from "../types";

export const FLOOR_PLAN: RoomData[] = [
  // ─── FLOOR 1 ───────────────────────────────────────────────────────────────
  {
    id: "101",
    floor: 1,
    name: "Room 101",
    cameraId: "",
    neighbors: ["102", "corridor_1"],
    isExit: true,
    isCorridor: false,
  },
  {
    id: "102",
    floor: 1,
    name: "Room 102",
    cameraId: "",
    neighbors: ["101", "103", "corridor_1"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "103",
    floor: 1,
    name: "Room 103",
    cameraId: "1A",
    neighbors: ["102", "104", "corridor_1"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "104",
    floor: 1,
    name: "Room 104",
    cameraId: "",
    neighbors: ["103", "105", "corridor_1"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "105",
    floor: 1,
    name: "Room 105",
    cameraId: "",
    neighbors: ["104", "106", "corridor_1"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "106",
    floor: 1,
    name: "Room 106",
    cameraId: "1B",
    neighbors: ["105", "107", "corridor_1"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "107",
    floor: 1,
    name: "Room 107",
    cameraId: "",
    neighbors: ["106", "108", "corridor_1"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "108",
    floor: 1,
    name: "Room 108",
    cameraId: "",
    neighbors: ["107", "corridor_1"],
    isExit: true,
    isCorridor: false,
  },
  {
    id: "corridor_1",
    floor: 1,
    name: "Corridor 1",
    cameraId: "",
    neighbors: [
      "101",
      "102",
      "103",
      "104",
      "105",
      "106",
      "107",
      "108",
      "stair_1_2",
    ],
    isExit: false,
    isCorridor: true,
  },
  {
    id: "stair_1_2",
    floor: 1,
    name: "Stairwell A (F1)",
    cameraId: "",
    neighbors: ["corridor_1", "stair_2_1"],
    isExit: false,
    isCorridor: true,
  },

  // ─── FLOOR 2 ───────────────────────────────────────────────────────────────
  {
    id: "201",
    floor: 2,
    name: "Room 201",
    cameraId: "",
    neighbors: ["202", "corridor_2"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "202",
    floor: 2,
    name: "Room 202",
    cameraId: "",
    neighbors: ["201", "203", "corridor_2"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "203",
    floor: 2,
    name: "Room 203",
    cameraId: "",
    neighbors: ["202", "204", "corridor_2"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "204",
    floor: 2,
    name: "Room 204",
    cameraId: "2A",
    neighbors: ["203", "205", "corridor_2"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "205",
    floor: 2,
    name: "Room 205",
    cameraId: "",
    neighbors: ["204", "206", "corridor_2"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "206",
    floor: 2,
    name: "Room 206",
    cameraId: "",
    neighbors: ["205", "207", "corridor_2"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "207",
    floor: 2,
    name: "Room 207",
    cameraId: "2B",
    neighbors: ["206", "208", "corridor_2"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "208",
    floor: 2,
    name: "Room 208",
    cameraId: "",
    neighbors: ["207", "corridor_2"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "corridor_2",
    floor: 2,
    name: "Corridor 2",
    cameraId: "",
    neighbors: [
      "201",
      "202",
      "203",
      "204",
      "205",
      "206",
      "207",
      "208",
      "stair_2_1",
      "stair_2_3",
    ],
    isExit: false,
    isCorridor: true,
  },
  {
    id: "stair_2_1",
    floor: 2,
    name: "Stairwell A (F2)",
    cameraId: "",
    neighbors: ["corridor_2", "stair_1_2"],
    isExit: false,
    isCorridor: true,
  },
  {
    id: "stair_2_3",
    floor: 2,
    name: "Stairwell B (F2)",
    cameraId: "",
    neighbors: ["corridor_2", "stair_3_2"],
    isExit: false,
    isCorridor: true,
  },

  // ─── FLOOR 3 ───────────────────────────────────────────────────────────────
  {
    id: "301",
    floor: 3,
    name: "Room 301",
    cameraId: "",
    neighbors: ["302", "corridor_3"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "302",
    floor: 3,
    name: "Room 302",
    cameraId: "3A",
    neighbors: ["301", "303", "corridor_3"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "303",
    floor: 3,
    name: "Room 303",
    cameraId: "",
    neighbors: ["302", "304", "corridor_3"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "304",
    floor: 3,
    name: "Room 304",
    cameraId: "",
    neighbors: ["303", "305", "corridor_3"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "305",
    floor: 3,
    name: "Room 305",
    cameraId: "3B",
    neighbors: ["304", "306", "corridor_3"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "306",
    floor: 3,
    name: "Room 306",
    cameraId: "",
    neighbors: ["305", "307", "corridor_3"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "307",
    floor: 3,
    name: "Room 307",
    cameraId: "",
    neighbors: ["306", "308", "corridor_3"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "308",
    floor: 3,
    name: "Room 308",
    cameraId: "3C",
    neighbors: ["307", "corridor_3"],
    isExit: false,
    isCorridor: false,
  },
  {
    id: "corridor_3",
    floor: 3,
    name: "Corridor 3",
    cameraId: "",
    neighbors: [
      "301",
      "302",
      "303",
      "304",
      "305",
      "306",
      "307",
      "308",
      "stair_3_2",
    ],
    isExit: false,
    isCorridor: true,
  },
  {
    id: "stair_3_2",
    floor: 3,
    name: "Stairwell B (F3)",
    cameraId: "",
    neighbors: ["corridor_3", "stair_2_3"],
    isExit: false,
    isCorridor: true,
  },
];

export const CAMERA_TO_ROOM: Record<string, string> = {
  "1A": "103",
  "1B": "106",
  "2A": "204",
  "2B": "207",
  "3A": "302",
  "3B": "305",
  "3C": "308",
};

export const ROOM_MAP = new Map<string, RoomData>(
  FLOOR_PLAN.map((r) => [r.id, r]),
);

export function getRoomsByFloor(floor: number): RoomData[] {
  return FLOOR_PLAN.filter((r) => r.floor === floor);
}
