/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ThreatResult = IDL.Record({
  'threatType' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : IDL.Text,
  'rawResponse' : IDL.Text,
  'confidence' : IDL.Nat,
});
export const RoomData = IDL.Record({
  'id' : IDL.Text,
  'floor' : IDL.Nat,
  'isCorridor' : IDL.Bool,
  'name' : IDL.Text,
  'isExit' : IDL.Bool,
  'neighbors' : IDL.Vec(IDL.Text),
  'cameraId' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'classifyAudio' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ThreatResult, 'err' : IDL.Text })],
      [],
    ),
  'classifyImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ThreatResult, 'err' : IDL.Text })],
      [],
    ),
  'computeEscapePath' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      ['query'],
    ),
  'generateEvacuationInstruction' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'generateTTS' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getFloorPlan' : IDL.Func([], [IDL.Vec(RoomData)], ['query']),
  'getLatestThreat' : IDL.Func([], [IDL.Opt(ThreatResult)], ['query']),
  'getOccupiedRooms' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSimulatorState' : IDL.Func([], [IDL.Opt(ThreatResult)], ['query']),
  'resetSimulator' : IDL.Func([], [], []),
  'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
  'setGoogleTtsApiKey' : IDL.Func([IDL.Text], [], []),
  'setOccupied' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'simulateFire' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'whoami' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ThreatResult = IDL.Record({
    'threatType' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : IDL.Text,
    'rawResponse' : IDL.Text,
    'confidence' : IDL.Nat,
  });
  const RoomData = IDL.Record({
    'id' : IDL.Text,
    'floor' : IDL.Nat,
    'isCorridor' : IDL.Bool,
    'name' : IDL.Text,
    'isExit' : IDL.Bool,
    'neighbors' : IDL.Vec(IDL.Text),
    'cameraId' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'classifyAudio' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ThreatResult, 'err' : IDL.Text })],
        [],
      ),
    'classifyImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ThreatResult, 'err' : IDL.Text })],
        [],
      ),
    'computeEscapePath' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        ['query'],
      ),
    'generateEvacuationInstruction' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'generateTTS' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getFloorPlan' : IDL.Func([], [IDL.Vec(RoomData)], ['query']),
    'getLatestThreat' : IDL.Func([], [IDL.Opt(ThreatResult)], ['query']),
    'getOccupiedRooms' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSimulatorState' : IDL.Func([], [IDL.Opt(ThreatResult)], ['query']),
    'resetSimulator' : IDL.Func([], [], []),
    'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
    'setGoogleTtsApiKey' : IDL.Func([IDL.Text], [], []),
    'setOccupied' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'simulateFire' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'whoami' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };