/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RoomData {
  'id' : string,
  'floor' : bigint,
  'isCorridor' : boolean,
  'name' : string,
  'isExit' : boolean,
  'neighbors' : Array<string>,
  'cameraId' : string,
}
export interface ThreatResult {
  'threatType' : string,
  'timestamp' : bigint,
  'severity' : string,
  'rawResponse' : string,
  'confidence' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'classifyAudio' : ActorMethod<
    [string, string],
    { 'ok' : ThreatResult } |
      { 'err' : string }
  >,
  'classifyImage' : ActorMethod<
    [string, string, string],
    { 'ok' : ThreatResult } |
      { 'err' : string }
  >,
  'computeEscapePath' : ActorMethod<
    [string, Array<string>],
    { 'ok' : Array<string> } |
      { 'err' : string }
  >,
  'generateEvacuationInstruction' : ActorMethod<
    [string, Array<string>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'generateTTS' : ActorMethod<[string], { 'ok' : string } | { 'err' : string }>,
  'getFloorPlan' : ActorMethod<[], Array<RoomData>>,
  'getLatestThreat' : ActorMethod<[], [] | [ThreatResult]>,
  'getOccupiedRooms' : ActorMethod<[], Array<string>>,
  'getSimulatorState' : ActorMethod<[], [] | [ThreatResult]>,
  'resetSimulator' : ActorMethod<[], undefined>,
  'setGeminiApiKey' : ActorMethod<[string], undefined>,
  'setGoogleTtsApiKey' : ActorMethod<[string], undefined>,
  'setOccupied' : ActorMethod<[string, boolean], undefined>,
  'simulateFire' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'whoami' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];